### ISSUE TITLE
 Perf events was supported?

### ISSUE THREAD

**Issue by annp1987** [dropbox/goebpf#13]
Hi,

The library is awesome!  Thanks for great work. 

But I wonder whether it already supported BPF_PERF_EVENT_OUTPUT() helper?

**Comment by belyalov** [comment]
Hi,
Thanks for warm words :)

Currently it is not supported, we have plans to add support, likely in Q1 of 2020.
But feel free to add it! ;)

Contributions are warmly welcomed!

**Comment by belyalov** [comment]
@annp1987 FYI: I've started on adding support for perf events.. :)

**Comment by annp1987** [comment]
@belyalov : Wow. That sounds great! I'm looking forward to seeing it.

**Comment by calavera** [comment]
Hi @belyalov, is there a branch that people can see with the initial implementation?

I was wondering the same thing this morning. I'll be more than happy to help if it's blocked or you don't have much time to focus on it right now.

**Comment by belyalov** [comment]
@calavera - project start postponed for a ~2 weeks, no currently no any WIP branch...

**Comment by belyalov** [comment]
Update: project has been started and likely will be finished next week 🎉

**Comment by belyalov** [comment]
Hi @calavera,

Initial, dirty and incomplete implementation is ready.
If you still interested check the `perf_events` branch.. :)

Happy holidays.
