### ISSUE TITLE
mocks: A proposal to override default implementation

### ISSUE THREAD

**Issue by simar7** [dropbox/goebpf#14]
Hello,

First of all, thank you for working on this library. So far I've had a very positive experience using it, especially with the included examples and documentation.

I do have one suggestion regarding the mocks package. What are your thoughts on providing a way to override the default implementation each mock has? To give you an example:

Currently the `LoadElf()` method from `mock_ebpf.go` looks something like the following:
```
func (m *MockSystem) LoadElf(fn string) error {
	return nil
}
```

This is great but it doesn't let the user override with a different behaviour for `LoadElf()`, one that could be potentially a non happy-path that returns an error. So with that in mind it would look something like the following:

```
func (m *MockSystem) LoadElf(fn string) error {
        if m.loadElf != nil {
             return m.loadElf(fn)
        }
	return nil
}
```

Where loadElf is a member of the struct `MockSystem` and can be overriden as needed during a unit test where various implementations of `LoadElf()` are needed.

Let me know your thoughts, I can draft a PR to incorporate this.

**Comment by belyalov** [comment]
Hi,

Thanks for positive feedback! Really appreciated! :)

It looks like you just want `LoadElf()` function to return `error` for some cases?
How about something like that then?
```go
func (m *MockSystem) LoadElf(fn string) error {
	return m.ErrorForLoadElf
}

// ...
    ms.ErrorForLoadElf = someError
    ms.LoadElf(someFile)
```

**Comment by simar7** [comment]
Hey @belyalov  that's correct and what I intended to do. But it seems that `MockSystem` currently doesn't have `ErrorForLoadElf` as a member to be able to assign. Did I miss something?

**Comment by belyalov** [comment]
It currently does not, for sure :)
Feel free to add it with documentation and submit PR :)

**Comment by belyalov** [comment]
@simar7 support has been added. Enjoy! :)

**Comment by simar7** [comment]
Thanks! @belyalov
