### ISSUE TITLE
Question on BPF_MAP_TYPE_HASH lookup errors

### ISSUE THREAD

**Issue by RebelIT** [dropbox/goebpf#26]
Hi there, I have been running in to issue trying to read a hash type map with this goebpf package.  Is that supported yet?  no matter which lookup type i try results in `ebpf_map_lookup_elem() failed: No such file or directory`.

map def: 
```
BPF_MAP_DEF(stat) = {
    .map_type = BPF_MAP_TYPE_HASH,
    .key_size = sizeof(__u32),
    .value_size = sizeof(__u64),
    .max_entries = MAX_BPF_IP,
};
BPF_MAP_ADD(stat);
```
populating it with key ip_stat and value is a counter.
```
struct ip_stat {
    __u32 saddr;
    __u32 daddr;
    __u32 action;
    __u8 proto;
};
```

**Comment by RebelIT** [comment]
I should clarify i'm trying to iterate through all keys in a hash map being populated by the xdp prog. Not just lookup one k/v pair.

**Comment by belyalov** [comment]
Hi @RebelIT 

Have you tried to run integration tests? (they are under `itest` directory).
We have `hash_maps` covered here (you can use it as example as well):
https://github.com/dropbox/goebpf/blob/master/itest/map_test.go#L19
Also, could you please provide more context (like `go` part)?

Regarding iteration through all items in the hash - support has not added yet.

**Comment by belyalov** [comment]
Closed due inactivity.
Please feel free to reopen.
