### ISSUE TITLE
Attach the same program to multiple interfaces

### ISSUE THREAD

**Issue by chenwng** [dropbox/goebpf#37]
Hi,

Does xdpProgram support attaching the same program to multiple interfaces? As far as I can tell from the code, a xdpProgram has one ifname and only detach the the program from this interface. If multiple Attach() are called with different interfaces, only the last one will be detached in the Detach() call. Is this intended? Is there any way to attach the same program to different interfaces?

Thanks!

**Comment by belyalov** [comment]
Hi,

It is not supported by design: one system/xdp_program -> one interface. Otherwise additional complexity will be introduced only for this particular program type / usecase.

But nothing stops you to create few instances of `ebpf.System`, like this:

```go
xdps := map[string]goebpf.System{}

for _, iface := range []string{"eth0", "eth1"} {
    bpf := goebpf.NewDefaultEbpfSystem()
    bpf.LoadElf("test.elf")
    xdp := bpf.GetProgramByName("xdp_test")
    xdp.Load()
    xdp.Attach(iface)

    xdps[iface] = bpf
}
```

It will take more memory, but, remains simple.

**Comment by chenwng** [comment]
Thanks for the reply!

I suppose the way you provided will create two progs and two set of maps, and progs cannot share data via maps any more. That may not work in my case.  I am creating some DNAT application, which accepts connection on one interface and modifies the dst address and saves the session info in the map and forwards the packet via another interface. When the return packet arrives on the another interface, a lookup in the map will be done to restore the address.  I understand this can be achieved with two progs with different functions each attaching to different interfaces, but this will make the progs not so common and may require prog array if the same interface is used for both incoming and outgoing purpose. 

Currently I crafted my own Detach() to release interfaces based on the logic of xdpProgram one. But this is a hack of the goebpf package.

**Comment by belyalov** [comment]
> I suppose the way you provided will create two progs and two set of maps, and progs cannot share data via maps any more.

By default - yes, maps will not be shared. However it is super easy to make them shared across different programs / processes / etc:
https://github.com/dropbox/goebpf/blob/4910d571d799ca6c94728f5aad303c0f154a831f/itest/ebpf_prog/xdp1.c#L8-L14

Please be sure to mount destination as `bpffs`
```
mount bpffs -t bpffs /sys/fs/bpf
```

**Comment by chenwng** [comment]
Thanks for the advice. I will try it. This can be closed.
