### ISSUE TITLE
all tests fail 

### ISSUE THREAD

**Issue by themighty1** [dropbox/goebpf#44]
I compiled tests with `make` and ran them with `sudo ./itest_test`
All tests failed with errors like

`            	            	loadAndCreateMaps() failed: map.Create() failed: ebpf_create_map() failed: Operation not permitted`

`            	            	ebpf_create_map() failed: Operation not permitted
`

go version go1.15.7 linux/amd64
Ubuntu 20.04 kernel 5.8.0-41

**Comment by themighty1** [comment]
running 
`go test -v -coverprofile=coverage.txt -covermode=atomic`
PASSED

**Comment by belyalov** [comment]
Did you mount `/sys/fs/bpf` as `bpffs`?

It maybe done by something like
```bash
$ mount bpffs -t bpffs /sys/fs/bpf
```

**Comment by themighty1** [comment]
Restarting the machine made this problem go away.
Thank you.
